# Generated by Django 4.2 on 2023-05-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indx_no_field', models.IntegerField()),
                ('name_field', models.CharField(max_length=10)),
                ('place_field', models.CharField(max_length=10)),
                ('course_field', models.CharField(max_length=10)),
            ],
        ),
    ]
