# Generated by Django 4.0.6 on 2022-12-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('dep', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employee.department')),
            ],
        ),
    ]
