# Generated by Django 4.0.6 on 2022-12-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
