# Generated by Django 4.1.7 on 2023-03-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_mypic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypic',
            old_name='image',
            new_name='image_s',
        ),
    ]
