# Generated by Django 4.2.5 on 2023-09-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('sub', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='cover/')),
                ('pdf', models.FileField(upload_to='files/')),
            ],
        ),
    ]
