# Generated by Django 4.2.5 on 2023-09-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
