# Generated by Django 4.2.5 on 2023-09-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='sts',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crudapp.assignment_status'),
        ),
    ]
