# Generated by Django 4.2.5 on 2023-09-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_alter_assignments_sts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='sts',
        ),
    ]
