# Generated by Django 4.2.5 on 2023-09-30 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_remove_assignments_sts'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='as_st',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crudapp.assignment_status'),
        ),
    ]
