# Generated by Django 4.2.5 on 2023-09-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0007_assignments_as_st'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='as_st',
        ),
    ]
