# Generated by Django 4.2.5 on 2023-09-30 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0009_assignments_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
