# Generated by Django 4.2.5 on 2023-09-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0010_alter_assignments_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignments',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
